#!/bin/sh

dir="${HOME}/cedit"
path="${HOME}/cedit/bin"

if [ "${PWD}" != "${dir}" ]
then
  rm -rf ${dir}
  mkdir ${dir}
  cp -r * ${dir}
fi

if [ "${OS}" = "Windows_NT" ]
then
  ${path}/setting.exe
else
  ${path}/setting
fi

if [ ! `echo ${PATH} | grep -e ${path}` ]
then
  echo 'export PATH=${PATH}:'"${path}" >> ${HOME}/.bashrc
  . ${HOME}/.bashrc
fi

if [ "${OS}" = "Windows_NT" ] && [ ! `alias | grep -e cedit` ]
then
  echo "alias cedit='cedit.exe'" >> ${HOME}/.bashrc
  . ${HOME}/.bashrc
fi
